name: 🚀 Manual Release

on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  detect-release:
    name: 🔍 Detect if Release Needed
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.check.outputs.should_release }}
      bump_type: ${{ steps.check.outputs.bump_type }}
      feature_count: ${{ steps.check.outputs.feature_count }}
      fix_count: ${{ steps.check.outputs.fix_count }}
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: 📥 Install dependencies
        run: npm ci

      - name: 🔍 Analyze commits for release
        id: check
        run: npx tsx scripts/should-release.cts

  release:
    name: 🚀 Create Release
    runs-on: ubuntu-latest
    needs: detect-release
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: 📦 Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: 🤖 Configure Git
        run: |
          git config --global user.email "shrizzon@gmail.com"
          git config --global user.name "Samuel Rizzon"

      - name: 📥 Install dependencies
        run: npm ci

      - name: 📊 Release Summary (Pre)
        run: |
          echo "## 🎯 Release Analysis" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Bump Type**: ${{ needs.detect-release.outputs.bump_type }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Features**: ${{ needs.detect-release.outputs.feature_count }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Fixes**: ${{ needs.detect-release.outputs.fix_count }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

      - name: 🎯 Run Nx Release
        id: nx_release
        run: |
          echo "Git status before release:"
          git status
          echo ""
          echo "Bump type detected: ${{ needs.detect-release.outputs.bump_type }}"
          echo ""

          # Check if there are any existing release tags
          if git describe --tags --abbrev=0 2>/dev/null; then
            echo "Found existing tags, running normal release"
            npx nx release --skip-publish --preid=beta --verbose ${{ needs.detect-release.outputs.bump_type }}
          else
            echo "No existing tags found, running first release"
            npx nx release --skip-publish --first-release --preid=beta --verbose ${{ needs.detect-release.outputs.bump_type }}
          fi

          echo ""
          echo "Git status after release:"
          git status
          echo ""
          echo "Recent commits:"
          git log --oneline -3
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: 🏷️ Push Changes and Tags
        run: |
          echo "Checking git status before push..."
          git status
          echo ""
          echo "Checking for new tags..."
          git tag -l --sort=-version:refname | head -5
          echo ""
          echo "Pushing changes and tags..."
          git push origin master --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: 🎉 Success Summary
        run: |
          # Extract the new version from the last tag
          NEW_VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "unknown")

          echo "## ✅ Release Created Successfully!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ "$NEW_VERSION" != "unknown" ]; then
            echo "### 🏷️ Version" >> $GITHUB_STEP_SUMMARY
            echo "\`$NEW_VERSION\`" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          fi

          echo "### 📦 Next Steps" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ CHANGELOG.md updated" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Version bumped in package.json" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Git tag created" >> $GITHUB_STEP_SUMMARY
          echo "- 🚀 NPM publish workflow will be triggered automatically" >> $GITHUB_STEP_SUMMARY
          echo "- 📝 GitHub Release will be created" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ "$NEW_VERSION" != "unknown" ]; then
            echo "### 🔗 Links" >> $GITHUB_STEP_SUMMARY
            echo "- [View on GitHub](https://github.com/${{ github.repository }}/releases/tag/$NEW_VERSION)" >> $GITHUB_STEP_SUMMARY
            echo "- [View Changelog](https://github.com/${{ github.repository }}/blob/master/CHANGELOG.md)" >> $GITHUB_STEP_SUMMARY
          fi
